name: msds2026-ml3-intro
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - matplotlib
  - pandas
  - ipykernel
  - python
  - scikit-learn
  - seaborn
  - pip
  - keras=3.13.2
  - tensorflow=2.19.0
  - numpy
  - pytorch=2.10.0
  - jax=0.7.2
  - pip:
    - ipywidgets
    - pydot
